# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Hackcancer' do
    
pod 'Overcoat/ReactiveCocoa'
pod 'PureLayout'

end

target 'HackcancerTests' do

